language: node_js
deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: www.discor.co
    skip_cleanup: true # prevents resetting and deleting all changes
